# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  neovim = {
    pname = "neovim";
    version = "5d03caed282b27612c305f79def7b50b45c3de58";
    src = fetchFromGitHub {
      owner = "kbeerta";
      repo = "kbeerta.nvim";
      rev = "5d03caed282b27612c305f79def7b50b45c3de58";
      fetchSubmodules = false;
      sha256 = "sha256-6LJ8Zi6HssTq7NmvkOT6pZK4/NhoLb2XThZcqs4Nm0c=";
    };
    date = "2025-02-02";
  };
}
