# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  neovim = {
    pname = "neovim";
    version = "4334bc5801cdbe4b9ba44910d5b8d84cb3e2d24f";
    src = fetchFromGitHub {
      owner = "kbeerta";
      repo = "kbeerta.nvim";
      rev = "4334bc5801cdbe4b9ba44910d5b8d84cb3e2d24f";
      fetchSubmodules = false;
      sha256 = "sha256-aRBW7WUGRqB85GfxgMzlI11gKEB03SGeWIR7s9uk/8E=";
    };
    date = "2025-02-05";
  };
}
