# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  neovim = {
    pname = "neovim";
    version = "d38bb4c322475c8c37ca102958d3ba48f487b37f";
    src = fetchFromGitHub {
      owner = "kbeerta";
      repo = "kbeerta.nvim";
      rev = "d38bb4c322475c8c37ca102958d3ba48f487b37f";
      fetchSubmodules = false;
      sha256 = "sha256-sZNLmVDi3qFkNVWtyAyC2VDUi/lZLCVOldZiWfIxIvQ=";
    };
    date = "2025-02-25";
  };
}
