
unbind C-b
set -g prefix C-a
bind a send-prefix
bind C-a last-window

bind-key x kill-pane

set -g default-terminal "tmux-256color"
set -sa terminal-features ",foot-extra:RGB"

set -s escape-time 0
set-option -g allow-rename off

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour colour5

# pane borders
set -g pane-border-style 'fg=colour5'
set -g pane-active-border-style 'fg=colour13'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=colour5'
set -g status-left ''
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50
set -g status-left-length 10

setw -g window-status-current-style 'fg=colour0 bg=colour5 bold'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=colour5 dim'
setw -g window-status-format ' #I #[fg=colour7]#W #[fg=colour5]#F '

setw -g window-status-bell-style 'fg=colour4 bg=colour5 bold'

