
# defaults
set -s escape-time 0

set -g mouse on
set -g base-index 1
set -g default-terminal "tmux-256color"

# keybindings
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind-key x kill-pane
bind-key & kill-window

setw -g mode-keys vi

# statusbar
set -g status on
set -g status-interval 1
set -g status-justify left
set -g status-position bottom

set -g status-keys vi
set -g status-style fg=colour5

# miscellaneous
set -g visual-bell off
set -g bell-action none
set -g visual-silence off
set -g visual-activity off

setw -g monitor-activity off

