[window]
padding = { x = 5, y = 5 }

[font]
size = 10
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors.primary]
background = "#000100"

