[general]
import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

[window]
padding = { x = 5, y = 5 }

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors.primary]
background = "#1a1a1a"
foreground = "#fefefe"
